name: trash_bin_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.3.2
  flutter_local_notifications: ^18.0.0
  google_fonts: ^6.2.1
  http: ^1.2.2
  mobile_scanner: ^6.0.2
  qr_scanner_overlay: ^0.0.2
  geolocator: ^13.0.2
  intl: ^0.19.0
  geocode: ^1.0.3
  geocoding: ^3.0.0
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets: 
    - .env